### ISSUE TITLE
Discontinue meeting recordings

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/lang-team#100]
# Proposal

## Summary and problem statement

By recording our meetings, we're closing out voices we want to hear from, and making people feel uncomfortable and not fully safe speaking freely. We've had multiple people report to us that they're not comfortable participating in recorded meetings. In addition, as a secondary consideration, recording and posting these videos takes a substantial amount of lang team leadership bandwidth.

We propose to stop recording lang team meetings. In order to preserve transparency, we will continue to enforce the "no new rationale" policy, and in particular, we won't make decisions where the only record of the decision or rationale is in the meeting. Anything discussed in a public meeting will be captured in some combination of public minutes, posts to public GitHub issues, public Zulip discussions, and/or Inside Rust blog posts.

## What happens now?

This issue is part of the experimental MCP process described in [RFC 2936]. Once this issue is filed, a Zulip topic will be opened for discussion, and the lang-team will review open MCPs in its weekly triage meetings. You should receive feedback within a week or two.

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[MCP]: https://forge.rust-lang.org/lang/mcp.html
[forge]: https://forge.rust-lang.org/
[RFC 2936]: https://github.com/rust-lang/rfcs/pull/2936/

**Comment by jhpratt** [comment]
While my opinion isn't particularly relevant, I'd be fine with this as long as minutes are kept as intended. It would honestly be quicker to read through too, making this a win-win imo.

**Comment by nrc** [comment]
I think it is very useful to have meeting recordings. As a data point, I'm trying to get up to speed on the deref patterns work. Despite there being a lot of comments and docs around, having a recording of the 2021-02-09 meeting (https://www.youtube.com/watch?v=KNemhVm8kgA&t=35s) was invaluable to understand the lang team's position on the topic and gave me a much better understanding than reading the MCP issue or Zulip chats (which often summarised or referenced the meeting, but missed some detail).

I think there is a trade-off between allowing people outside the team to fully understand the team's position on issues, and members of the team (or potential members) being able to talk more freely or be more comfortable. I would propose that you might have a private section of the meeting (if you don't already) to address the former. I'm not sure how to address the latter and I acknowledge it might be an issue in making the team more inclusive. However, I think that being able discuss issues in a transparent and open manner is a key quality for leaders in the Rust community to develop, so the solution might be mentoring to make people feel more comfortable, rather than removing this source of discomfort.
