### ISSUE TITLE
impl Trait Sync-up

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/lang-team#127]
# Summary

Discuss upcoming plans for impl Trait stabilization and expansion.

# Background reading

https://hackmd.io/5MakNcwCRDKWnP6UTL58wg

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds
to a possible topic of discussion that may be scheduled for deeper discussion
during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/design-meeting.html

**Comment by nikomatsakis** [comment]
Minutes: https://github.com/rust-lang/lang-team/blob/master/design-meeting-minutes/2021-11-17-named-fn-types.md

**Comment by comex** [comment]
`However, this construction has two shortcomings. First, it is not stable, because we wish to keep room to adopt variadic generics later, so we have not hard-coded the tuple in `FnOnce<>`. (Using the `FnOnce(A1, A2, A3)` shorthand means specifying the value of the Output associated type, and if we could do that we wouldn't need this feature!)`

An alternative might be to use the `_` placeholder, making `FnOnce(A1, A2, A3) -> _` shorthand for `FnOnce<(A1, A2, A3)>` without an `Output` bound.  Although perhaps there's some way that could be a breaking change?
