### ISSUE TITLE
extern macro!(ABI) fn

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/lang-team#151]
# Proposal

## Summary and problem statement

Today, there are cases where the ABI in `extern ABI` should be selected based on static properties, such as the target architecture.

I propose we fix this by making `extern macro!(ABI) fn` work. This way, people will not have to write duplicate definitions under `#[cfg(...)]` attributes to get the same effect.

## Motivation, use-cases, and solution sketches

Today in Rust, there are cases where the same function definition can work for distinct ABI's depending on target. But you cannot merge them into one definition; you have to use separate function items with distinct `#[cfg(...)]` attributes.

For example, [this comment](https://github.com/rust-lang/rust/issues/42202#issuecomment-1006213947) describes a scenario where this leads to code duplication (at the level of signature and body) between an `extern "thiscall" fn` on i686-windows and an `extern "fastcall" fn` on x86_64-windows.

If we made the ABI in `extern ABI` a macro expansion position, then the above would be easy to resolve: someone who has literally the same definition for both cases would write an appropriate macro to expand the right way. (I have sketched an idea like `extern cfg_match!(target_arch, "x86" => "thiscall", "x86_64" => "fastcall") fn foo() {}`, but this initiative is not about what specific macro to use; it is about *enabling* macros to be used at all.

## Links and related work

Inspired by [suggestion](https://github.com/rust-lang/rust/issues/42202#issuecomment-1007152534) from @DrMeepster

[backlog bonanza discussion](https://zulip-archive.rust-lang.org/stream/238009-t-compiler/meetings/topic/.5Bsteering.20meeting.5D.202022-03-18.20compiler-team.23484.html#275811339)

## Initial people involved

- Owner, if known: pnkfelix
- Liaison

## What happens now?

This issue is part of the lang-team [initiative process]. Once this issue is filed, a Zulip topic will be opened for discussion, and the lang-team will review open proposals in its weekly triage meetings. You should receive feedback within a week or two.

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[forge]: https://forge.rust-lang.org/
[initiative process]: https://lang-team.rust-lang.org/initiatives.html

**Comment by DrMeepster** [comment]
I already started to write an RFC for this before, how exactly would that fit into the initiative process? I don't have any experience with this process.

**Comment by Lokathor** [comment]
The goal of the process is to help you with the RFC writing, so that once the RFC is eventually posted as a pr to the rfc repo it's had more eyes on it, more revisions if necessary, and hopefully the pr itself is a smoother process. Since this is a fairly small change that doesn't touch much of the language you might end up having a suitable RFC draft fairly quickly anyway.

**Comment by pnkfelix** [comment]
also, @DrMeepster, I didn't mean to step on any toes. As I said, I was inspired by [your comment](https://github.com/rust-lang/rust/issues/42202#issuecomment-1007152534) to take action here, but I did not know that you had already started drafting a formal RFC.

The language and compiler team have both been working on identifying lighterweight methodologies that have smaller stages with explicit intermediate goals. @nikomatsakis and I both agreed that this would be a language team issue, but not one that requires a ton of effort.

In particular I am thinking we can use the language team [initiative process](https://lang-team.rust-lang.org/initiatives.html) and get started on a prototype implementation, while the RFC process moves forward in parallel.

**Comment by nikomatsakis** [comment]
I don't think an RFC is necessarily required here -- this feels like a pretty small change.

**Comment by nikomatsakis** [comment]
I'm going to move to **close** this proposal instead, putting it into FCP for *that*.

**Comment by thomcc** [comment]
I've wanted this in libsqlite3-sys to switch between `extern "C" { ... }` blocks and `extern "system" { ... }` blocks depending on whether we're linking against `winsqlite3.dll` (which is the same as sqlite3 except shipped with the OS and uses a different ABI on 32-bit windows. Don't ask, as it is I force use of bindgen for winsqlite3 for this reason).

This is a slightly different case, which doesn't have the problem that raised the main objection.

It would be unfortunate to need to use proc macros for this case, because it would break use on static targets (which I currently support), and it would slow down builds. Honestly, I'd rather just have two binding files (currently libsqlite3-sys has many, although I'm trying to get away from this).

**Comment by scottmcm** [comment]
We briefly discussed this in today's lang meeting, and agreed to close as disposed.

We're content with the possible alternative approaches here, be that
- Adding or defining *specific* ABIs to have the needed semantics, if sufficiently motivated.
- Using an attribute macro to add it to a declaration or definition.
- Using an enclosing macro to add it to potentially many things.

---

@thomcc for blocks in particular, it might not be that bad to have 
```rust
extern_custom! {
    fn foo(x: i32) -> i32;
    fn bar(y: u32) -> u32;
}
```
With a `cfg`'d definition of the macro_rules attribute.

Enclosing macros are somewhat more painful for definitions, but for declarations that might be a tolerable way that doesn't need the extra complexity of a proc macro.

**Comment by thomcc** [comment]
FWIW the lack of something like this is also part of why rusqlite will not be supporting winsqlite3 on 32 bit code, since it needs a different API for callbacks as well.

That said I'm somewhat fine with that since I'm highly inclined to remove support for winsqlite3 all together (SQLite with size opts enabled is under 1MB of code, it's really not worth the pain to bundle...)

**Comment by thomcc** [comment]
> @thomcc for blocks in particular, it might not be that bad to have
> 
> ```rust
> extern_custom! {
>     fn foo(x: i32) -> i32;
>     fn bar(y: u32) -> u32;
> }
> ```

This is mostly fine, but doesn't work for callbacks. For example, consider a `my-c-lib-sys` which defines its ABI as conditionally `"C"` or `"system"`, which has callbacks with the same ABI. For example:

```rs
#[cfg(ffi_needs_extern_system)]
macro_rules extern_c_or_system {  ($($ts:tt)*) => { extern "system" { $($ts)* } }
#[cfg(not(ffi_needs_extern_system))]
macro_rules extern_c_or_system {  ($($ts:tt)*) => { extern "C" { $($ts)* } }

#[cfg(ffi_needs_extern_system)]
pub type my_c_lib_some_callback_t = unsafe extern "system" fn() -> c_int;
#[cfg(not(ffi_needs_extern_system))]
pub type my_c_lib_some_callback_t = unsafe extern "C" fn() -> c_int;

extern_c_or_system! {
    pub fn my_c_lib_do_thing(callback: my_c_lib_some_callback_t) -> c_int;
}
```

(Imagine `ffi_needs_extern_system` is emitted by build.rs depending on whether we're liking against a version of the library provided by recent versions of windows -- this kind of thing happens for SQLite, ICU, and some other large C libraries that have `extern "system"`-using versions bundled on Win10+)

This basically works fine... until you try to use it from a downstream crate (for example, a higher-level safe Rust crate wrapping the `my_c_lib` API). The issue is: how does such a crate define the callback function to pass into `my_c_lib_do_thing`? It needs to conditionally decide based on which ABI is needed, which isn't something it knows (since only the `-sys` crate knows that, as it's determined by the build.rs).

[^1]: Okay, you could type dispatch based on the type of `my_c_lib_some_callback_t`, *I guess*.

However, if ABI-position macros were supported, `my-c-lib-sys` could contain:
```rs
#[macro_export]
#[cfg(ffi_needs_extern_system)]
macro_rules callback_abi {  () => { "system" } }

#[macro_export]
#[cfg(not(ffi_needs_extern_system))]
macro_rules callback_abi {  () => { "C" } }
```

and then the downstream high level crate could use this macro as follows for function pointers passed into `my-c-lib-sys`:

```rs
use my_c_lib_sys::{callback_abi, my_c_lib_do_thing};

extern callback_abi!() fn my_callback(_: c_int) -> c_int { ... }

let ret = my_c_lib_do_thing(my_callback);
// ...
```

I'm not sure how you could make this work with the suggested alternatives without a great deal of pain (in practice, the best solution seems like adding trampolines to the `-sys` crate, although I guess there are some very awkward approaches (based on our existing macro capabilities) that would work too).

*(Concretely, this is the reason that even with code generation, it's too painful to support linking with winsqlite3.dll for `libsqlite3-sys` and I imagine the same situation is true for stuff like the ICU dlls that are provided by win10+, etc).*

**Comment by thomcc** [comment]
Another use case for this came up recently.

As I understand it, when `feature(c_unwind)` stabilizes, if you need to use unwind out of `extern` functions, or call `extern` functions that unwind, you must immediately switch to using `extern "C-unwind"`, as using `extern "C"` for this will break right away. This is, at least, the behavior of the current `#![feature(c_unwind)]` -- if you turn the feature on, `extern "C"` is no longer usable (within your crate) and you must use `extern "C-unwind"`.

This means libraries that need to handle this will have to use version detection/probing/etc in their Cargo.toml to detect availability.

If macro-position ABI worked still, applying this would be a matter of something like this:

```rs
#[cfg(have_c_unwind)]
macro_rules! c_unwind {
    () => { "C-unwind" };
}

#[cfg(not(have_c_unwind))]
macro_rules! c_unwind {
    () => { "C" };
}

extern c_unwind!() { fn foo(); }
extern c_unwind!() fn bar() { ... }
```
which is quite simple, and obvious to write, doesn't require adding a separate crate (which must also detect the feature) and can be easily re-exported for users in a way they don't have to worry about the issue.

**Comment by thomcc** [comment]
Is there any way this can be reconsidered?

I've given a few examples above of cases that have come up where I've wanted this feature or could use it, and I'll explain why I think the reason for closing this above is not convincing to me.

Sadly, I didn't realize this when the FCP was active (or I found it unconvincing but didn't care much, and have since hit this issue many times...)

From @nikomatsakis's [comment](https://github.com/rust-lang/lang-team/issues/151#issuecomment-1075519139):

> @cramertj raised a key objection that, in this instance, it was a bit unclear that this macro ought to expand to an ABI string _in particular_. Given that the ABI part of an `extern fn` is optional, one could imagine the `f!()` in `extern f!()` might expand to a function or to other modifiers (e.g., `unsafe`).

There is a reason that it ought to expand to an ABI string in particular: It is common not to the right ABI to use until build time. It may depend on the target (of course), the library linked against (`winsqlite3.dll` vs `libsqlite3.dll` use different ABIs), and even the Rust compiler version (in the case of `"$abi-unwind"` [discussed above](https://github.com/rust-lang/lang-team/issues/151#issuecomment-1303414244) and possibly in the case of new ABIs). This logic is complex, and is best isolated to a single place, likely a build script for a library containing the functions in question.

Conversely, whether or not a function needs `unsafe` is essentially never conditionally dependent on build-time settings, as that's a very static property. While it's possible to come up with hypothetical reasons they might be, it's very hard to imagine realistic ones. Similarly, it's unlikely that there would be a reason to export that use of conditional unsafe to dependent crates (and I imagine it would tend to upset people if they did).

Furthermore, function-modifier-position macros would not solve this problem fully -- ABI strings are also part of `extern $abi {...}` blocks, so would need special consideration there too.

---

> Another point against this proposal was that it would be quite easy to write a procedural macro that "rewrites" the ABI of functions, so that e.g.
> ```rs
> #[rewrite_win_abi]
> extern "stdcall" fn foo() { }
> ```
> could look at the target and adjust the ABI accordingly.

This doesn't really work well. For one, the logic is quite complex and may be specific to the library in question (see the headaches I mentioned above about winsqlite3.dll (provided by OS) using a different ABI than other windows SQLite distributions).

More importantly, this does not solve the issue for down-stream consumers. That is, if `foo_sys` has `extern "C" { fn bar(extern "stdcall" fn()); }` sometimes and `extern "C" { fn bar(extern "cdecl" fn()); }` other times, then consumers of `foo_sys` need to match that logic for the declaration of the callback function passed to bar. I give a more complete example of this in [this comment](https://github.com/rust-lang/lang-team/issues/151#issuecomment-1254512149), and will spare y'all the code blocks

(While in theory you could probably do this with a proc-macro per ABI that is re-exported conditionally, it is quite a bit of work for something that can be accomplished with a very trivial declarative macro)

---

Anyway, I hope that's somewhat convincing? The lack of support of this is fairly painful in FFI code, and seems like this problem is coming up more and more frequently, both as we add more ABIs which may need to be conditionally selected (and perhaps as the windows ecosystem grows).

Please let me know if you have questions.
