### ISSUE TITLE
Meeting proposal: rename "object safety" to "dyn compatibility"

### ISSUE THREAD

**Issue by notriddle** [rust-lang/lang-team#286]
# Summary

Instead of calling them "object safe," refer to traits that support vtables as being "dyn compatible."

# Background reading

https://internals.rust-lang.org/t/object-safety-is-a-terrible-term/21025

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds to a possible topic of discussion that may be scheduled for deeper discussion during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/meetings/design.html

**Comment by joshtriplett** [comment]
We talked about this at today's meeting, and we're generally in favor of making this change. Starting an FCP to confirm.

@rfcbot merge

**Comment by traviscross** [comment]
cc @ehuss

**Comment by fmease** [comment]
I'll open PRs for rustc and the std lib shortly.

**Comment by traviscross** [comment]
I've created a tracking issue for this here:

- https://github.com/rust-lang/rust/issues/130852

**Comment by cher-nov** [comment]
To be honest, the whole "[trait object](https://doc.rust-lang.org/1.82.0/reference/types/trait-object.html)" term is awful.

1. Traits themselves are not instantiable and therefore cannot be "objects" in the common sense of this word. Quite the contrary: it is a type that is the _subject_ of trait-specific behavior.

2. This term has a strong association with the object-oriented paradigm and thereby is simply misleading. I understand the obvious need to refer to "[dynamic dispatch](https://en.wikipedia.org/wiki/Dynamic_dispatch)", "[late binding](https://en.wikipedia.org/wiki/Late_binding)" and "[virtual methods](https://en.wikipedia.org/wiki/Virtual_function)", but it would be much more logical just to use this term and make a disclaimer "you know, this is [what we use](https://doc.rust-lang.org/1.82.0/book/ch17-00-oop.html) instead of OOP in this (part of the) universe".

See, for example, here for an example of confusion:
https://stackoverflow.com/questions/27567849/what-makes-something-a-trait-object

Frankly, I'd be happy to see one day an RFC covering reduction of the amount of self-inflicted and arbitrarily homegrown terminology in Rust, with the case of UFCS term misuse being an obvious example of this from the past.
https://en.wikipedia.org/w/index.php?title=Uniform_Function_Call_Syntax&oldid=1247021182#Rust_usage_of_the_term
https://github.com/rust-lang/rfcs/pull/3366
I do not consider writing such an RFC myself due to lack of the Rust language knowledge (I am still learning it) and the ashaming level of my English.

**Comment by notriddle** [comment]
> To be honest, the whole "[trait object](https://doc.rust-lang.org/1.82.0/reference/types/trait-object.html)" term is awful.

Yes, the language team officially agrees. [Here's the tracking issue](https://github.com/rust-lang/rust/issues/130852) for renaming it everywhere.
